server:
  port: 8082

spring:
  application:
    name: article-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/articledb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

snowflake:
  datacenter-id: 1
  worker-id: 1

jwt:
  secret: secret-key-must-be-at-least-256-bits-long-so-make-it-long-enough

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/articledb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
